CREATE SEQUENCE task_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE tasks (
    id BIGINT NOT NULL CONSTRAINT tasks_pk PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);